### ISSUE TITLE
Suppress LDAP warnings and errors

### ISSUE THREAD

**Issue by dlancea** [Dreamscapes/Ldap-Core#2]
With the native LdapExceptions being raised, it's redundant to have the native LDAP warnings and errors.

Maybe set and un-set an error handler before and after native function calls to make sure all errors and warnings are thrown as exceptions?

This could be an option set in the constructor of Dreamscapes\Ldap\Core\Ldap

**Comment by Alaneor** [comment]
I think I will probably opt in to the error suppression (`@`) - I just did some tests (have a look [here](https://github.com/Tyrael/php-microbenchmarks)) and for PHP 5.6 a custom error handler increased the execution time from 3s to a whopping 42s when there is an error in the code.

In real life, this should not be that dramatic, but it seems much easier to just suppress the errors and always check `ldap_errno` (which we are already doing).

The reason why I have not done so yet is that I have not had enough time to battle-test the library in a production environment and I wanted to make sure I got it all right.

Have you perhaps had a chance to test it? Does it throw properly when there are errors?

**Comment by Alaneor** [comment]
This is now implemented in the `dev-develop` [Composer target](https://packagist.org/packages/dreamscapes/ldap-core) - feel free to test it out! Any feedback is much appreciated. The relevant commit, if you are interested, is a77fa7f.

This will be released as **2.1**, but no ETA so far on release date (as usual with open-source software :) ).

**Comment by Alaneor** [comment]
Released in *3.0.0*.
