### ISSUE TITLE
Paged search

### ISSUE THREAD

**Issue by Furgas** [Dreamscapes/Ldap-Core#3]
How should I, using this library, approach searching with pagination as shown in "Example *#*2 LDAP pagination" on http://php.net/manual/en/function.ldap-control-paged-result.php ?

**Comment by Alaneor** [comment]
That's simple! You can request the data to be returned to you in pages by first [enabling paged responses](http://dreamscapes.github.io/Ldap-Core/classes/Dreamscapes.Ldap.Core.Ldap.html#method_pagedResult) before you send your search query.

Once you have a [response](http://dreamscapes.github.io/Ldap-Core/classes/Dreamscapes.Ldap.Core.ResultResource.html), you can extract the cookie from it via [this method](http://dreamscapes.github.io/Ldap-Core/classes/Dreamscapes.Ldap.Core.ResultResource.html#method_pagedResultResponse). You will need to use the cookie on subsequent requests as the last parameter of the `pagedResult()` method.

So the whole process looks like this:

1. Call `resultResponse()` with no cookie set (you do not have one yet)
1. Perform search query
1. Extract cookie from response (if any!) using `pagedResultResponse()`
1. If there is cookie, repeat process from step 1, but set the cookie to the cookie you just got
1. If there is no cookie in the response, your dataset is complete

**Comment by Furgas** [comment]
Thanks. Before I asked the questions, I tried to search for ldap_control_paged_result_response with github search but found nothing.

The paged search process calls for some helper method.

**Comment by Alaneor** [comment]
It's [here](https://github.com/Dreamscapes/Ldap-Core/blob/master/Dreamscapes/Ldap/Core/ResultResource.php#L60). :)

Github fails to find this function call because of the *@* before it. Searching for *\@ldap_control_paged_result_response* does the trick.

**Comment by jrjohnson** [comment]
After some messing around I ended up with this code which seems to work.
```php
$results = [];
$cookie = '';
 do {
     $ldap->pagedResult(1000, false, $cookie);
     $response = $ldap->search($this->ldapSearchBase, $filter, $attributes);
     $arr = $response->getEntries();
     unset($arr['count']);
     $results = array_merge($results, $arr);
     $pagedArray = $response->pagedResultResponse();
     $cookie = !empty($pagedArray['cookie'])?$pagedArray['cookie']:false;
 } while ($cookie);
```

**Comment by Alaneor** [comment]
Optionally you can do

         $cookie = $response->pagedResultResponse("cookie");

Which will give you just the cookie.
